WEBSOCKET ws://localhost:7331/water-sty/scrolling
Content-Type: application/json // used only for IDE highlighting.
// Highlighting is applied for each message independently.


{
    "message": "Send when the WebSocket connection is opened"
}
=== wait-for-server
{
    "message": "Wait for the server message and send the current message as response"
}
===
{
    "message": "Send after previous message without waiting for the server message"
}

###
