@startuml

start

:获取手机号码;
:获取验证码;


:查看手机号是否存在;
if (用户存在？) then (是)
    :获取用户信息;
else (否)
    :创建新用户;
endif

:获取缓存中的验证码;
if (验证码正确？) then (是)
    :删除缓存中的验证码;
    if (用户不存在？) then (是)
        :创建用户;
        :创建用户信息;
    endif
    :进行登录;
else (否)
    :抛出参数错误异常;
endif

stop

@enduml
