@startuml

start

:获取当前用户ID;
:获取关注分组ID列表;
:获取当前用户关注的UP主ID;
:根据用户ID和UP主ID从数据库中获取已关注的分组ID列表;
if (已关注的分组ID列表不为空？) then (是)
    :遍历已关注的分组ID列表;
    :删除数据库中当前用户关注的指定UP主的所有关注分组;
endif
:设置关注对象的用户ID为当前用户ID;
:遍历关注分组ID列表;
:设置关注对象的分组ID为当前遍历的分组ID;
:向数据库中添加关注对象到指定分组;

stop

@enduml
