@startuml

start

:检查参数searchDto是否为空;
:获取搜索内容;
:构建分页信息;
:根据搜索内容查询视频信息;
if (内容为空？) then (是)
    :查询所有视频信息;
else (否)
    :根据视频名称模糊查询视频信息;
endif
:构建PageResult对象;
:设置总数为查询结果的大小;
:遍历查询结果;
:过滤出审核通过且状态正常的视频信息;
:设置过滤后的视频信息到PageResult对象;
:设置总页数为查询结果的总页数;
:设置当前页码为查询结果的页码加一;
:设置总元素数为查询结果的总元素数;
:返回PageResult对象;

stop

@enduml
