@startuml

start

:登录;
if (登录成功？) then (是)
  :进入创作界面;
  :上传视频分片;
  :分析视频信息;
  if (视频分析成功？) then (是)
    :填写作品名称;
    :填写封面;
    :填写简介;
    :上传;
    if (上传成功？) then (是)
      :管理员审核;
      if (审核通过？) then (是)
        :上传成功;
      else (否)
        :上传被拒绝;
      endif
    else (否)
      :上传失败;
    endif
  else (否)
    :上传失败;
  endif
else (否)
  :登录失败;
endif

end

@enduml
